"""Modify database scheme.

Revision ID: 0fd8aef89452
Revises: None
Create Date: 2016-04-09 20:07:26.671000

"""

# revision identifiers, used by Alembic.
revision = '0fd8aef89452'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body_html',
                    new_column_name='body_html_cache',
                    existing_type=sa.Text())
    op.alter_column('posts', 'summary_html',
                    new_column_name='summary_html_cache',
                    existing_type=sa.String(length=1024))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body_html_cache',
                    new_column_name='body_html',
                    existing_type=sa.Text())
    op.alter_column('posts', 'summary_html_cache',
                    new_column_name='summary_html',
                    existing_type=sa.String(length=1024))
    ### end Alembic commands ###
